name: Filmify
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.5
  http: ^0.13.6
  fade_shimmer: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.otf